### ISSUE TITLE
nyuEshelfToolbarController not setting logged in status correctly on first visit

### ISSUE THREAD

**Issue by barnabyalter** [NYULibraries/primo-explore-nyu-eshelf#1]
When a user logs into PDS in Primo Classic and then visits the NUI they are seen as a logged in user  but the e-shelf button says "Guest e-Shelf" until after a refresh. It is not picking up the logged in scope correctly.

In `nyuEshelfToolbarController` we set `loggedIn` flag in `onInit` like this:

```
this.$onInit = function() {
  $scope.loggedIn = !this.primoExploreCtrl.userSessionManagerService.isGuest();
}
```

https://github.com/NYULibraries/primo-explore-nyu-eshelf/blob/master/js/nyu-eshelf.module.js#L215

**Comment by etgrieco** [comment]
I've been playing around with this a lot, and unfortunately at this point can only conclude it's a vendor issue.

To reproduce:
1) Go to http://bobcat.library.nyu.edu/primo-explore/search?vid=NYU-NUI&sortby=rank&lang=en_US
2) Login
3) Close all windows/tabs related to bobcat.
4) Renavigate to http://bobcat.library.nyu.edu/primo-explore/search?vid=NYU-NUI&sortby=rank&lang=en_US
5) User's name should be displayed, but the appropriate login state is not.

However, for some reason if any other tab is open with bobcat logged in, then there is a noticeable 'double-load' on the page, in addition to the appropriate 'My Eshelf' text being shown.

Unfortunately, it is impossible to replicate this bug in the devenv, which makes it very tricky to see if there is a way to temporarily resolve it on our end.

**Comment by barnabyalter** [comment]
@etgrieco It's entirely possible it's a vendor issue but I think there are still some things to exhaust. 

We should check out the difference between how we're setting the `loggedIn` variable at https://github.com/NYULibraries/primo-explore-nyu-eshelf/blob/master/js/nyu-eshelf.module.js#L154 and https://github.com/NYULibraries/primo-explore-nyu-eshelf/blob/master/js/nyu-eshelf.module.js#L215, the former references this factory (https://github.com/NYULibraries/primo-explore-nyu-eshelf/blob/master/js/nyu-eshelf.module.js#L62) the latter does not.

They're using `$scope` and `$onInit` slightly differently too. And though it is very difficult for me to consistently reproduce, when I can reproduce the checkbox has the correct state but the top-right button does not.

All that being said this is not a real use-case after we retire the classic bobcat so if it's not relatively easy to fix we shouldn't spend too much time.

**Comment by etgrieco** [comment]
@barnabyalter issue resolved by removing my/guest eshelf text from toolbar.  Implemented in https://github.com/NYULibraries/primo-explore-nyu-eshelf/pull/6
